# 03 — Order-support agent without tools (using create_agent)
#
# Concept: An agent graph without tools cannot see live order data —
# the model must guess or refuse.
#
# Building on lesson 02:
#   In Section 03, we built raw StateGraph loops by hand.
#   In lesson 02, we introduced create_agent() as the modern standard.
#   Here we build our Acme order-support agent with create_agent() (tools omitted).
#
# Limitation overcome: Deciding to build an order-support agent instead of a fixed chain.
# Still limited: ORDERS exists in process memory, but the agent has no tools to read it.
#
# Example: Ask status of ORD-1 — agent has no lookup tool and must decline.
#
# ```mermaid
# flowchart LR
#   START --> model
#   model --> END
# ```

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.messages import HumanMessage

load_dotenv()

# Live database in process memory — but agent has NO tool access to it yet!
ORDERS = {"ORD-1": "shipped", "ORD-2": "pending"}

# ════════════════════════════════════════════════════════════════════════════
# PART 1: Create agent without tools (high-level API)
# ════════════════════════════════════════════════════════════════════════════

print("═" * 100)
print("ORDER SUPPORT AGENT (NO TOOLS)")
print("═" * 100)
print()

# KEY CODE SNIPPET: create_agent without tools
# No tools passed → creates a minimal graph: START → model → END
agent = create_agent(
    model="groq:openai/gpt-oss-20b",
    system_prompt=(
        "You are order support for ORD-* tickets. "
        "You have NO live order database. Be honest if unsure."
    ),
)

# Inspect the compiled graph generated by create_agent
print("Compiled graph structure (no tool loop):")
print(agent.get_graph().draw_mermaid())
print("-" * 100)

# ════════════════════════════════════════════════════════════════════════════
# PART 2: Querying the agent
# ════════════════════════════════════════════════════════════════════════════

print("ORDERS in application memory (agent cannot access):", ORDERS)
print()

question = "What is the status of ORD-1?"
print(f"Customer Question: {question}")

response = agent.invoke({"messages": [HumanMessage(content=question)]})
answer = response["messages"][-1].content

print(f"Agent Answer: {answer}")
print()

print("═" * 100)
print("EXAMPLE OUTPUT:")
print("═" * 100)
print("Customer Question: What is the status of ORD-1?")
print("Agent Answer: I apologize, but I do not have access to the live order database")
print("              to check the status of ORD-1. Please provide more details or contact support.")
print("-" * 100)

# ════════════════════════════════════════════════════════════════════════════
# KEY CONCEPTS & PROGRESSION
# ════════════════════════════════════════════════════════════════════════════

print("═" * 100)
print("WHY THIS MATTERS")
print("═" * 100)
print()
print("1. NO MANUAL BOILERPLATE:")
print("   • No need to define TicketState, add_messages, or StateGraph by hand.")
print("   • create_agent() handles state management and graph compilation.")
print()
print("2. THE NEED FOR TOOLS:")
print("   • Prompting alone cannot bridge the gap to external databases.")
print("   • Even though ORDERS is in memory, the model cannot inspect Python variables.")
print()
print("3. NEXT LESSON (04.order_support_agent.py):")
print("   • We pass tools=[lookup_order, list_orders] to create_agent().")
print("   • The graph automatically expands to: START → model ↔ tools → END.")
print("-" * 100)
