# 04 — Order-support agent with tools (using create_agent)
#
# Concept: Bind lookup tools to an agent loop so answers come directly from live data.
#
# Progression from lesson 03:
#   In lesson 03, create_agent had no tools and had to decline.
#   In lesson 04, we add tools=[lookup_order, list_orders] to create_agent.
#   The compiled graph automatically adds the model ↔ tools loop!
#
# Limitation overcome: Without tools the agent cannot see ORD-1 / ORD-2 status.
# Same ticket agent as before — now ORDERS is available via tools.
# Still limited: Risky actions (refunds) run without human approval (fixed in lesson 05).
#
# Example: Look up ORD-1 status and list all orders.
#
# ```mermaid
# flowchart TD
#   START --> model
#   model -->|tool_calls| tools
#   tools --> model
#   model -->|done| END
# ```

from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.messages import HumanMessage
from langchain.tools import tool

load_dotenv()

ORDERS = {"ORD-1": "shipped", "ORD-2": "pending"}


# ════════════════════════════════════════════════════════════════════════════
# PART 1: Define tools
# ════════════════════════════════════════════════════════════════════════════

@tool
def lookup_order(order_id: str) -> str:
    """Look up order status by id (e.g. ORD-1)."""
    return ORDERS.get(order_id, f"Order {order_id} not found")


@tool
def list_orders() -> str:
    """List all orders and their current statuses."""
    return ", ".join(f"{k}={v}" for k, v in ORDERS.items())


tools = [lookup_order, list_orders]

# ════════════════════════════════════════════════════════════════════════════
# PART 2: Create agent with tools (high-level API)
# ════════════════════════════════════════════════════════════════════════════

print("═" * 100)
print("ORDER SUPPORT AGENT (WITH TOOLS)")
print("═" * 100)
print()

# KEY CODE SNIPPET: create_agent with tools
# Passing tools=[...] automatically wires the tool loop into the graph!
agent = create_agent(
    model="groq:openai/gpt-oss-20b",
    tools=tools,
    system_prompt="You are order support for ORD-* tickets. Use tools to look up live order data.",
)

# Inspect the compiled graph generated by create_agent with tools
print("Compiled graph structure (tool loop active):")
print(agent.get_graph().draw_mermaid())
print("-" * 100)

# ════════════════════════════════════════════════════════════════════════════
# PART 3: Querying the agent
# ════════════════════════════════════════════════════════════════════════════

for q in ["Status of ORD-1?", "List all orders"]:
    print(f"Customer Question: {q}")
    r = agent.invoke({"messages": [HumanMessage(content=q)]})
    print(f"Agent Answer: {r['messages'][-1].content}\n")

print("═" * 100)
print("EXAMPLE OUTPUT:")
print("═" * 100)
print("Customer Question: Status of ORD-1?")
print("Agent Answer: Order ORD-1 has been shipped.")
print()
print("Customer Question: List all orders")
print("Agent Answer: Here are all current orders: ORD-1=shipped, ORD-2=pending.")
print("-" * 100)

# ════════════════════════════════════════════════════════════════════════════
# KEY CONCEPTS
# ════════════════════════════════════════════════════════════════════════════

print("═" * 100)
print("KEY TAKEAWAYS")
print("═" * 100)
print()
print("1. SEAMLESS PROGRESSION (03 → 04):")
print("   • Lesson 03: create_agent(model=..., system_prompt=...) → no tools")
print("   • Lesson 04: create_agent(model=..., tools=[...], system_prompt=...) → with tools")
print("   • The graph automatically adds the 'tools' node and conditional edges.")
print()
print("2. UNDER THE HOOD:")
print("   • Section 03 taught the raw StateGraph, ToolNode, and tools_condition plumbing.")
print("   • create_agent() abstracts that exact plumbing into a clean, single function call.")
print()
print("3. WHAT'S NEXT (05.human_in_the_loop.py):")
print("   • Lookup tools are safe (read-only).")
print("   • But refund tools mutate state and spend money — they need human approval.")
print("-" * 100)
